import psycopg2
import random
import time
from datetime import datetime
import logging
from psycopg2 import OperationalError
from psycopg2.extras import execute_batch

# Configure logging for debugging and monitoring
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# PostgreSQL configuration for connecting to the database
db_config = {
    'dbname': 'factory_log',
    'user': 'admin',
    'password': 'password',
    'host': 'postgres',
    'port': '5432'
}

# Sample data synchronized with init.sql for random log generation
products = ['Product X', 'Product Y', 'Product Z']
stations = ['Station 1', 'Station 2', 'Station 3', 'Station 4']
lines = ['Line 1', 'Line 2', 'Line 3']
factories = ['Factory A', 'Factory B']
equipment = ['EQ123', 'EQ124', 'EQ125', 'EQ126']
workers = ['John Doe', 'Jane Smith', 'Bob Johnson']
shifts = ['SHIFT001', 'SHIFT002', 'SHIFT003']
errors = [None, 'ERR001', 'ERR002', 'ERR003']
work_orders = ['WO001', 'WO002', 'WO003']
statuses = ['Completed', 'Failed', 'In Progress']

def connect_with_retry(max_attempts=5, delay=5):
    """
    Attempt to connect to PostgreSQL with retries.
    Args:
        max_attempts (int): Maximum number of connection attempts
        delay (int): Seconds to wait between attempts
    Returns:
        psycopg2.connection: Database connection
    Raises:
        Exception: If connection fails after max attempts
    """
    attempts = 0
    while attempts < max_attempts:
        try:
            conn = psycopg2.connect(**db_config)
            logger.info("Successfully connected to PostgreSQL")
            return conn
        except OperationalError as e:
            attempts += 1
            logger.warning(f"Connection attempt {attempts}/{max_attempts} failed: {e}")
            if attempts == max_attempts:
                logger.error("Max connection attempts reached. Exiting.")
                raise
            time.sleep(delay)
    return None

def generate_product_log():
    """
    Generate a random product log based on sample data (without 'quantity').
    Returns:
        tuple: Product log data (excluding id, auto-generated by PostgreSQL)
    """
    return (
        f'SN{random.randint(100, 999)}',  # serial_number
        datetime.utcnow(),  # timestamp
        random.choice(products),  # product_name
        random.choice(stations),  # station_name
        random.choice(lines),  # line_name
        random.choice(factories),  # factory_name
        random.choice(equipment),  # equipment_serial
        random.choice(workers),  # worker_name
        random.choice(shifts),  # shift_code
        random.choice(errors),  # error_code
        random.choice(work_orders),  # work_order_name
        random.choice(statuses)  # status (no 'quantity' column now)
    )

def insert_product_logs(conn, logs):
    """
    Insert multiple product logs into the product_log table using batch insert.
    Args:
        conn (psycopg2.connection): Database connection
        logs (list): List of product log tuples
    """
    try:
        with conn.cursor() as cur:
            query = """
                INSERT INTO product_log (
                    serial_number, timestamp, product_name, station_name, line_name,
                    factory_name, equipment_serial, worker_name, shift_code, error_code,
                    work_order_name, status
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """  # Removed 'quantity' from the INSERT query
            execute_batch(cur, query, logs)
            conn.commit()
            logger.info(f"Inserted {len(logs)} product logs")
    except Exception as e:
        logger.error(f"Failed to insert product logs: {e}")
        conn.rollback()

def main():
    """
    Main function to generate and insert 10 product logs every second.
    Connects to PostgreSQL, generates logs, and inserts in batches.
    """
    conn = connect_with_retry()
    try:
        while True:
            # Generate 10 product logs
            logs = [generate_product_log() for _ in range(10)]
            insert_product_logs(conn, logs)
            time.sleep(1)  # Insert every 1 second
    except KeyboardInterrupt:
        logger.info("Stopping data generator")
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
    finally:
        if conn:
            conn.close()
            logger.info("Database connection closed")

if __name__ == '__main__':
    main()
